### ISSUE TITLE
Workflow does not work for me.

### ISSUE THREAD

**Issue by mahsash** [jaspervdh96/Workflow#29]
Hello. I am the second grader for a course. I cannot make it work on my system. But the main instructor can.

When I try to run cells in workflow.ipynb, right on the second cell (and after a successful run for the first cell) I get this error:

`OperationalError: (sqlite3.OperationalError) no such column: assignment.course_id`

**Comment by jaspervanderheide** [comment]
Do you have nbgrader 0.6.0?

**Comment by mahsash** [comment]
Yes, I do.
And I can not see enything in "Formgrader" tab (which I think can be related to the same problem I have).

**Comment by jaspervanderheide** [comment]
Okay I haven't had the time to make the workflow working with nbgrader 0.6 yet, so you have downgrade I fear to nbgrader 0.5.5

**Comment by jaspervanderheide** [comment]
O I just realised, this will maybe also fix your other problem, because the database was made in 0.5.5, and I remember reading that that makes it incompatible. Sorry!

**Comment by mahsash** [comment]
Thank you! I downgraded nbgrader to 0.5.6 and now it works fine!
