### ISSUE TITLE
Data Science

### ISSUE THREAD

**Issue by maartenmarx** [jaspervdh96/Workflow#5]
Hi jas,

Kan jij,

* de cijfers van herdeeltoets1 en herdeeltoets2 opnieuw naar Canvas zetten?
* in de FAQ aangeven hoe je (ik) zo'n canvas API krijg en waar ik dat opgeef zodat ik dat nu ook zelf kan?

cheers!

**Comment by jaspervanderheide** [comment]
Gedaan, moet ik ook de eindcijfers updaten?
